import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../../components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
        <Header></Header>
        <div className="p-6 pt-32 max-w-4xl mx-auto">
          {children}
        </div>
        </main>
        </body>
    </html>
  );
}
